# Generated by Django 3.1.2 on 2020-10-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': True, 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'managed': True, 'verbose_name_plural': 'Order Details'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name_plural': 'Products'},
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='quantity',
            new_name='cuantity',
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='demo.order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderdetails', to='demo.product'),
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together={('order', 'product')},
        ),
    ]
